version: '3.8'

services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - '18000:8080'
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: sample
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: sample
    restart: always
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
