version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '18000:8080'
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: test
      DB_NAME: test
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - test-db-data:/var/lib/mysql
volumes:
  test-db-data:
